title: "xnlogic tutorials"
#author: "Blog Author"
description: "A collection of tutorials for the xnlogic framework."
#subheading: "Really cool blog about ... something"
more: "Go to the tutorial ..."
#url: "http://niklabs.me"
baseurl: "/getting_started" # comment out if in root directory

#comments:
#    disqus: "niklasbuschmann"
#    isso: "comments.mysite.org"

style:
    #body: "whitesmoke"
    padding: 25%
    anchor: "#46f"
    serif-heading: true
    nav: "#e7e7e7"
    #headline: "#a6f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  # - github: "https://github.com/me/"
  # - twitter: "https://twitter.com/me/"
  # - google-plus: "https://plus.google.com/+me"
  # - reddit: "https://www.reddit.com/user/me/"
  # - youtube: "https://www.youtube.com/user/me"
  # - steam: "http://steamcommunity.com/id/me/"
  - xnlogic: "http://xnlogic.com"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
